// Missão 3/livros-react/src/LivroLista.js
import React, { useState, useEffect } from 'react';
import ControleLivros from './controle/ControleLivros';
import ControleEditora from './controle/ControleEditora';
import 'bootstrap/dist/css/bootstrap.css';

const controleLivro = new ControleLivros();
const controleEditora = new ControleEditora();

const LivroLista = () => {
    const [livros, setLivros] = useState([]);
    const [carregado, setCarregado] = useState(false);

    useEffect(() => {
        const obterLivros = async () => {
          const livrosObtidos = await controleLivro.obterLivros();
          setLivros(livrosObtidos);
          setCarregado(true);
        };
    
        if (!carregado) {
          obterLivros();
        }
      }, [carregado]);

      const excluir = (codigo) => {
        controleLivro.excluir(codigo);
        setCarregado(false);
      };
    
      return (
        <main class="w-75 mx-auto">
            <h1>Catálogo de Livros</h1>
            <table class="table-striped w-100">
                <thead>
                    <tr class="bg-dark text-white">
                        <td style={{padding: "15px"}}>Título</td>
                        <td style={{padding: "15px"}}>Resumo</td>
                        <td style={{padding: "15px"}}>Editora</td>
                        <td style={{padding: "15px"}}>Autores</td>
                    </tr>
                </thead>
                <tbody>
                    {livros.map((livro) => (
                    <LinhaLivro key={livro.codigo} livro={livro} excluir={excluir} />
                    ))}
                </tbody>
            </table>
        </main>
      );
    }

const LinhaLivro = ({ livro, excluir }) => {
    const nomeEditora = controleEditora.getNomeEditora(livro.codEditora);
    return (
        <tr>
            <td>{livro.titulo}<button class="btn btn-danger d-block" onClick={() => excluir(livro.codigo)}>Excluir</button></td>
            <td>{livro.resumo}</td>
            <td>{nomeEditora}</td>
            <td>
                <ul>
                {livro.autores.map((autor, index) => (
                    <li key={index}>{autor}</li>
                ))}
                </ul>
            </td>
        </tr>
    )
}

export default LivroLista;

// Missão 4/livros-angular/src/app/livro-lista/livro-lista.component.ts
import { Component, OnInit } from '@angular/core';
import Editora from '../editora';
import Livro from '../livro';
import ControleEditoraService from '../controle-editora.service';
import ControleLivrosService from '../controle-livros.service';

@Component({
  selector: 'app-livro-lista',
  templateUrl: './livro-lista.component.html',
  styleUrls: ['./livro-lista.component.css']
})
export class LivroListaComponent implements OnInit {
  public editoras: Array<Editora> = [];
  public livros: Array<Livro> = [];

  constructor(
    private servEditora: ControleEditoraService,
    private servLivros: ControleLivrosService
  ) { }

  ngOnInit(): void {
    this.editoras = this.servEditora.getEditoras()

    this.livros = this.servLivros.obterLivros()
  }

  excluir(codigo: number): void {
    this.servLivros.excluir(codigo)
    this.livros = this.servLivros.obterLivros()
  }

  obterNome = (codEditora: number): string => {
    return this.servEditora.getNomeEditora(Number(codEditora));
  };
}

<main class="d-flex flex-column justify-content-center align-items-center" style="width: 100% !important;">
  <h2 class="w-75">Livro Lista</h2>
  <table class="table table-striped w-75">
    <thead class="thead-dark">
      <tr>
        <th>Título</th>
        <th>Resumo</th>
        <th>Editora</th>
        <th>Autores</th>
      </tr>
    </thead>
    <tbody>
      <tr *ngFor="let livro of livros">
        <td>
            {{ livro.titulo }}
            <button class="btn btn-danger d-block mt-2" (click)="excluir(livro.codigo)">
                Excluir
            </button>
        </td>
        <td>
            {{ livro.resumo }}
        </td>
        <td>
            {{ obterNome(livro.codEditora) }}
        </td>
        <td>
            <ul>
              <li *ngFor="let autor of livro.autores">{{ autor }}</li>
            </ul>
          </td>
      </tr>
    </tbody>
  </table>
</main>
