// Missão 4/livros-angular/src/app/livro-dados/livro-dados.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import Editora from '../editora';
import Livro from '../livro';
import ControleEditoraService from '../controle-editora.service';
import ControleLivrosService from '../controle-livros.service';

@Component({
  selector: 'app-livro-dados',
  templateUrl: './livro-dados.component.html',
  styleUrls: ['./livro-dados.component.css']
})
export class LivroDadosComponent implements OnInit {
  public livro: Livro = new Livro(0, 0, '', '', [])
  public autoresForm: string = '';
  public editoras: Array<Editora> = [];

  constructor(
    private servEditora: ControleEditoraService,
    private servLivros: ControleLivrosService,
    private router: Router
  ) { }

  ngOnInit(): void {
    this.editoras = this.servEditora.getEditoras();
  }

  incluir = (): void => {
    this.livro.autores = this.autoresForm.split('\n');
    this.servLivros.incluir(this.livro);
    this.router.navigateByUrl('/lista');
  }
}

<main class="w-100 d-flex flex-column justify-content-center align-items-center">
<h2 class="w-75">Incluir Livro</h2>
<form class="w-75" (submit)="incluir()" ngNativeValidate>
    <div class="mb-3">
        <label for="titulo" class="form-label">Título</label>
        <input type="text" class="form-control" id="titulo" required [(ngModel)]="livro.titulo" name="titulo">
    </div>
    <div class="mb-3">
        <label for="resumo" class="form-label">Resumo</label>
        <textarea class="form-control" id="resumo" rows="4" [(ngModel)]="livro.resumo" name="resumo"></textarea>
    </div>
    <div class="mb-3">
        <label for="editora" class="form-label">Editora</label>
        <select class="form-control" id="editora" required [(ngModel)]="livro.codEditora" name="editora">
            <option *ngFor="let editora of editoras;" [value]="editora.codEditora">{{ editora.nome }}</option>
        </select>          
    </div>
    <div class="mb-3">
        <label for="autores" class="form-label">Autores</label>
        <textarea class="form-control" id="autores" rows="4" [(ngModel)]="autoresForm" name="autores"></textarea>
    </div>
        <button type="submit" class="btn btn-primary">Incluir</button>
    </form>
</main>

// Missão 3/livros-react/src/LivroDados.js
import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import ControleLivros from './controle/ControleLivros';
import ControleEditora from './controle/ControleEditora';

const LivroDados = () => {
  const controleLivro = new ControleLivros();
  const controleEditora = new ControleEditora();

  const opcoes = controleEditora.getEditoras().map(editora => ({
    value: editora.codEditora,
    text: editora.nome
  }));

  const [titulo, setTitulo] = useState('');
  const [resumo, setResumo] = useState('');
  const [autores, setAutores] = useState('');
  const [codEditora, setCodEditora] = useState(opcoes[0].value);

  const navigate = useNavigate();

  const tratarCombo = (event) => {
    const { value } = event.target;
    setCodEditora(Number(value));
  };

  const incluir = (event) => {
    event.preventDefault();
    const livro = {
      codigo: 0,
      titulo,
      resumo,
      autores: autores.split('\n'),
      codEditora
    };
    controleLivro.incluir(livro);
    navigate('/');
  };

  return (
    <main class="w-75 mx-auto">
      <h1>Cados do Livro</h1>
      <form onSubmit={incluir}>
        <div className="mb-3">
          <label htmlFor="titulo" className="form-label">Título</label>
          <input type="text" className="form-control" id="titulo" value={titulo} onChange={event => setTitulo(event.target.value)} required/>
        </div>
        <div className="mb-3">
          <label htmlFor="resumo" className="form-label">Resumo</label>
          <textarea className="form-control" id="resumo" value={resumo} onChange={event => setResumo(event.target.value)} required></textarea>
        </div>
        <div className="mb-3">
          <label htmlFor="editora" className="form-label">Editora</label>
          <select className="form-select" id="editora" value={codEditora} onChange={tratarCombo}>
            {opcoes.map(opcao => (
              <option key={opcao.value} value={opcao.value}>{opcao.text}</option>
            ))}
          </select>
        </div>
        <div className="mb-3">
          <label htmlFor="autores" className="form-label">Autores (um por linha)</label>
          <textarea className="form-control" id="autores" value={autores} onChange={event => setAutores(event.target.value)} required></textarea>
        </div>
        <button type="submit" className="btn btn-primary">Incluir</button>
      </form>
    </main>
  );
}

export default LivroDados;
